version: "3.9"
services:
  db:
    image: mysql:latest
    restart: always
    container_name: de_database
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - data:/var/lib/mysql
    command: /bin/sh -c "./run.sh"