// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SignalL is an autogenerated mock type for the SignalL type
type SignalL struct {
	mock.Mock
}

// TurnOn provides a mock function with given fields:
func (_m *SignalL) TurnOn() {
	_m.Called()
}

type mockConstructorTestingTNewSignalL interface {
	mock.TestingT
	Cleanup(func())
}

// NewSignalL creates a new instance of SignalL. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSignalL(t mockConstructorTestingTNewSignalL) *SignalL {
	mock := &SignalL{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
